### ISSUE TITLE
Release Flutter plugin for Atom

### ISSUE THREAD

**Issue by sethladd** [flutter/atom-flutter#17]
End result: there is a plugin in the Atom plugin repository called "Flutter" and it's for Flutter and it can help build Flutter apps :)

Presumably, the Flutter plugin has a dependency on the dartlang plugin.

**Comment by devoncarew** [comment]
blocked on https://github.com/flutter/atom-flutter-dev/issues/19

**Comment by devoncarew** [comment]
published; `flutter` will install `dartlang` if necessary. The next version of `dartlang` will also install `flutter` - in order to maintain feature parity for current users. We'll remove that back reference after a few dartlang versions.
