### ISSUE TITLE
Atom not detecting correct PATH setting when launched from Launcher (Ubuntu)

### ISSUE THREAD

**Issue by qchong** [flutter/atom-flutter#43]
Atom 1.1.0, flutter plugin 0.1.2, running on linux.

**Comment by devoncarew** [comment]
Which command is it not able to find? Flutter, adb? Or is it having trouble auto-locating an sdk?

**Comment by qchong** [comment]
More context:

When running a Flutter app with F5, Atom returns:
"Unable to find adb. Is "adb" in your path?"
"Unable to run application = no connected devices."

I confirmed that 'adb' is set in my $PATH variable. When I launched Atom from command line (via 'atom' command), it was able to run the project successfully (again, with F5).  

But when I closed Atom, and launched it again using the GUI launcher, the same error occurred.

**Comment by devoncarew** [comment]
OK, thanks for the context. We have a solution for this on the mac - we exec all shells in the user's default shell, not in the one that we were started in.

We could apply the same fix here, though I'm less familiar w/ unix and the possible side effects. Perhaps we could document for now that it's recommended to run atom from the command-line (or recommend that as the fix if they have path issue)?

**Comment by sethladd** [comment]
Thanks for the feedback! If this is still an issue, please open a request over in https://github.com/flutter/flutter/issues

In the meantime, we are closing down this issue tracker and redirecting users over to https://github.com/flutter/flutter/issues
