### ISSUE TITLE
Smart ',' for optional arguments

### ISSUE THREAD

**Issue by lukechurch** [flutter/atom-flutter#56]
Flutter makes extremely heavy use of optional arguments, which means that when adding or removing them you frequently get the wrong number of ','s separating the argument.

If we could check this and quietly suppress any excess trailing ',' in the same way that JSON maps allows, we could decrease the viscosity of the editing considerably.

E.g. I want the following to not cause an error:

```
              constraints: new BoxConstraints(
                minWidth: screen.width / 3,
                minHeight: screen.height - 1,
              )
```

**Comment by devoncarew** [comment]
+1. I think this is an open issue on the sdk repo.

**Comment by devoncarew** [comment]
Hmm, I was not able to find a ref to the sdk bug, but it is in there somewhere.

**Comment by eseidelGoogle** [comment]
The bug is internal.  Not sure why.  #23422984
