### ISSUE TITLE
Assertion failure when running on ios simulator

### ISSUE THREAD

**Issue by turnidge** [flutter/atom-flutter#57]
Hi Folks,

Trying the code lab and I'm getting some scary looking assertion falures when I run.  They look like this:

assertiond: assertion failed: 15D21 13C75: assertiond + 12188 [8CF1968D-3466-38B7-B225-3F6F5B64C552]: 0x1

![screen shot 2016-03-08 at 1 02 41 pm 2](https://cloud.githubusercontent.com/assets/4804200/13616350/6ea3e562-e52e-11e5-80f4-fd5623db2af3.png)

Atom 1.5.4, flutter plugin 0.2.1, running on macos.

**Comment by devoncarew** [comment]
Those are harmless (I believe). Tracked here: https://github.com/flutter/flutter/issues/1989.
