### ISSUE TITLE
When running, Atom does not respond

### ISSUE THREAD

**Issue by kingkazuma** [flutter/atom-flutter#61]
When running flutter project, Atom does not respond, and mobile screen is black. But it's ok when run 'flutter run' in the terminal.

In Atom, throw AssertionError

> flutter run --checked --debug-port=16237 --start-paused --device-id 086dd9a99dcf92d2 • flutter logs
> draw_image/ • checked mode • debug
> [Android] W/ActivityManager: getRunningAppProcesses: caller 10069 does not hold REAL_GET_TASKS; limiting output
> [Android] W/ActivityManager: getRunningAppProcesses: caller 10069 does not hold REAL_GET_TASKS; limiting output
> [Android] W/ActivityManager: getRunningAppProcesses: caller 10069 does not hold REAL_GET_TASKS; limiting output

**Comment by kingkazuma** [comment]
Linux version 4.2.0-1-amd64 (debian-kernel@lists.debian.org)  #1 SMP Debian 4.2.6-3
Atom 1.6.2 
Flutter package 0.2.1
Android 5.1.1

**Comment by sethladd** [comment]
Thanks for the feedback!

We're cleaning up this issue tracker so we can direct all new issues over to https://github.com/flutter/flutter/issues. 

If you are still experiencing this issue, please open a new ticket over at https://github.com/flutter/flutter/issues
