### ISSUE TITLE
Add setting to disable Flutter analysis

### ISSUE THREAD

**Issue by pylaligand** [flutter/atom-flutter#62]
Background: https://github.com/dart-lang/sdk/issues/26154

I'd like to be able to disable the lints generated by Flutter and control the style for my own project.

**Comment by sethladd** [comment]
Thanks for the feedback! This sounds like a general request for https://github.com/flutter/flutter/issues. I think you can now control your own analysis by putting a .analysis_options file in the root of your project, but I'm not sure. If you still want to dig into this, please open a request over in https://github.com/flutter/flutter/issues

We're cleaning up this issue tracker so we can direct all new issues over to https://github.com/flutter/flutter/issues.
