### ISSUE TITLE
Suggest adding a 'Send Feedback for Plugin'

### ISSUE THREAD

**Issue by branflake2267** [flutter/atom-flutter#77]
I'd suggest adding a menu item to send feedback for plugin. 

![screen shot 2017-04-28 at 9 29 41 am](https://cloud.githubusercontent.com/assets/1326504/25537892/468d0496-2bf5-11e7-9980-f027b533fb20.png)

**Comment by devoncarew** [comment]
Hi @branflake2267, thanks for the suggestions! This plugin is not actively maintained, and will like be discontinued in the near term (https://github.com/dart-atom/atom-flutter#status---discontinued). We're putting out efforts into the IntelliJ Flutter plugin -

**Comment by branflake2267** [comment]
ah ha, good to know. :)
